### PR TITLE
Make up for LF in last line of SSH key file

### PR DESCRIPTION
**Pull request by tats-u**
#147

- [ ] append additional test
  - convert PEM to OpenSSH
  - remove last LF

### CODE REVIEW

**Comment by tats-u** [comment]
Waiting for #157 & #164 to be fixed.

**Comment by MatthiasKunnen** [comment]
Might I ask why this PR is blocked by #164?

**Comment by tats-u** [comment]
@MatthiasKunnen This is because CIs triggered by ALL PRs from ANYONE other than the author ALWAYS fail.  We can NEVER tell whether they are due to us or not.

**Comment by shimataro** [comment]
@MatthiasKunnen
Secrets won't be passed to non-author's actions; PRs/pushs/etc.
It's for security reason.

@tats-u 
Thank you for your PR, I've unlocked draft and merged into [my branch](https://github.com/shimataro/ssh-key-action/tree/feature/ssh-key-lf).
I will check your PR on the branch.

**Pull request merged**
