### PR TITLE
Update to Node 20

### PR DESCRIPTION
**Pull request by princemaple**
per #266

### CODE REVIEW

**Comment by princemaple** [comment]
ping @shimataro :)

**Review by mgoppert — APPROVED** [review]

**Comment by paulAtSlim** [comment]
Did someone have contact to the dev? Or an alternative Action recommendation that can be used?

**Comment by shimataro** [comment]
Very sorry for the late reply.
I will check it in a few days!

**Comment by bob-hinrichs** [comment]
+1 on this! Is an update imminent? Thanks much.

**Comment by shimataro** [comment]
Now [v2.7.0](https://github.com/shimataro/ssh-key-action/releases/tag/v2.7.0) supports Node.js 20. Thank you all!!

**Pull request merged**
