### PR TITLE
Fix known_host clobbering

### PR DESCRIPTION
**Pull request by jacktuck**
Tested in a gh action

https://github.com/jacktuck/test-clone-bitbucket-in-actions/runs/981961456?check_suite_focus=true

### CODE REVIEW

**Comment by jacktuck** [comment]
Looks like you removed the repository secrets? Tests are ok on the fork. 

https://github.com/jacktuck/ssh-key-action/actions

**Comment by shimataro** [comment]
Sorry, I didn't notice it and already merged #151 !

**Comment by jacktuck** [comment]
No worries - my bad for not linking to it.

**Comment by shimataro** [comment]
@jacktuck 
Thank you. Your name is in [CHANGELOG](https://github.com/shimataro/ssh-key-action/blob/develop/CHANGELOG.md#210---2020-08-15)! 😃

**Pull request closed without merging**
